import torch
import torch.nn as nn
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))
from config import config

class PhysicsInformedLoss(nn.Module):
    """Computes the physics-informed loss for the GAN.

    This loss consists of four parts:
    1.  Adversarial Loss: How well the generator fools the discriminator.
    2.  Physics Loss: The difference between the spectra generated by the forward model
        from the generator's output and the target spectra.
    3.  Metric Loss: The difference between the key physical metrics (Q, FoM, etc.)
        calculated from the generated spectra and the target metrics.
    4.  Physical Error Feedback Loss: Feedback from the discriminator's physical error head.
    """
    def __init__(self, forward_model, lambda_physics=config.LAMBDA_PHYSICS, 
                 lambda_metric=config.LAMBDA_METRIC, lambda_pid=config.LAMBDA_PID_FEEDBACK):
        super().__init__()
        self.forward_model = forward_model
        self.lambda_physics = lambda_physics
        self.lambda_metric = lambda_metric
        self.lambda_pid = lambda_pid # New parameter for PID feedback weight
        self.mse_loss = nn.MSELoss()

    def forward(self, generated_struct, target_spectra, target_metrics, D_fake_real_score, physical_error_feedback):
        # 1. Adversarial Loss (from generator's perspective - wants to maximize D's output)
        adversarial_loss = -torch.mean(D_fake_real_score)

        # 2. Physics-informed Loss
        # Get the predicted spectra and metrics from the (pre-trained) forward model
        predicted_spectra, predicted_metrics = self.forward_model(generated_struct)

        physics_loss = self.mse_loss(predicted_spectra, target_spectra)

        # 3. Metric Loss (will be 0 if lambda_metric is 0)
        if self.lambda_metric > 0 and target_metrics is not None:
            predicted_metrics_cleaned = torch.nan_to_num(predicted_metrics, nan=0.0)
            target_metrics_cleaned = torch.nan_to_num(target_metrics, nan=0.0)
            metric_loss = self.mse_loss(predicted_metrics_cleaned, target_metrics_cleaned)
        else:
            metric_loss = torch.tensor(0.0, device=config.DEVICE)

        # 4. Physical Error Feedback Loss (new)
        # Generator wants to minimize this feedback, so it's added directly
        pid_feedback_loss = self.lambda_pid * torch.mean(physical_error_feedback)

        # Total Generator Loss
        total_loss = adversarial_loss + \
                     self.lambda_physics * physics_loss + \
                     self.lambda_metric * metric_loss + \
                     pid_feedback_loss # Add PID feedback loss

        return total_loss, adversarial_loss, physics_loss, metric_loss, pid_feedback_loss

def gradient_penalty(discriminator, real_samples, fake_samples):
    """Calculates the gradient penalty loss for WGAN-GP."""
    alpha = torch.randn(real_samples.size(0), 1).to(config.DEVICE)

    interpolated = (alpha * real_samples + ((1 - alpha) * fake_samples)).requires_grad_(True)
    
    # Discriminator now returns two outputs, we only need the real_fake_score for GP
    d_interpolated, _ = discriminator(interpolated)

    grad_outputs = torch.ones(d_interpolated.size()).to(config.DEVICE)

    gradients = torch.autograd.grad(
        outputs=d_interpolated,
        inputs=interpolated,
        grad_outputs=grad_outputs,
        create_graph=True,
        retain_graph=True,
    )[0]

    gradients = gradients.view(gradients.size(0), -1)
    gradient_norm = gradients.norm(2, dim=1)
    gp = torch.mean((gradient_norm - 1) ** 2)
    return gp